# Generated by Django 5.1.2 on 2024-10-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('compliance', models.BooleanField()),
                ('past_performance', models.FloatField()),
            ],
        ),
    ]
